export const FETCHING_STOCK_LIST = 'FETCHING_STOCK_LIST';
export type FETCHING_STOCK_LIST = typeof FETCHING_STOCK_LIST;

export const FETCHED_STOCK_LIST = 'FETCHED_STOCK_LIST';
export type FETCHED_STOCK_LIST = typeof FETCHED_STOCK_LIST;
